# Python 编程作业自动评分 Workflow 模板
# 
# 使用方法：
# 1. 复制此文件到 .gitea/workflows/grade.yml
# 2. 根据需要调整 Python 版本、依赖安装等
# 3. 确保 problem.yaml 中配置了正确的测试目录

name: autograde-python

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  python:
    runs-on: docker
    container: python:3.11
    timeout-minutes: 15
    
    steps:
      - name: Install git (CN mirror)
        run: |
          set -e
          for f in /etc/apt/sources.list /etc/apt/sources.list.d/*.list /etc/apt/sources.list.d/*.sources; do
            [ -f "$f" ] || continue
            sed -i -E 's|https?://deb.debian.org|http://mirrors.cloud.tencent.com|g' "$f" || true
            sed -i -E 's|https?://security.debian.org|http://mirrors.cloud.tencent.com/debian-security|g' "$f" || true
          done
          apt-get update -y
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends git ca-certificates
          rm -rf /var/lib/apt/lists/*
      
      - name: Checkout code
        env:
          TESTS_TOKEN: ${{ secrets.TESTS_TOKEN }}
          EXTERNAL_GITEA_HOST: ${{ secrets.EXTERNAL_GITEA_HOST }}
        working-directory: ${{ github.workspace }}
        run: |
          set -e
          GITEA_HOST=$(echo "${{ github.server_url }}" | sed 's|https\?://||' | cut -d'/' -f1)
          HOST="$GITEA_HOST"
          if echo "$GITEA_HOST" | grep -qi '^gitea'; then
            if [ -n "$EXTERNAL_GITEA_HOST" ]; then
              HOST="$EXTERNAL_GITEA_HOST"
            else
              HOST="49.234.193.192:3000"
            fi
          fi
          REPO="${{ github.repository }}"
          REF="${{ github.sha }}"
          
          git init -q .
          if [ -n "$TESTS_TOKEN" ]; then
            REMOTE_URL="http://oauth2:${TESTS_TOKEN}@${HOST}/${REPO}.git"
          else
            REMOTE_URL="http://${HOST}/${REPO}.git"
          fi
          git remote add origin "$REMOTE_URL" || git remote set-url origin "$REMOTE_URL"
          git fetch --depth=1 origin "$REF"
          git checkout -q FETCH_HEAD
      
      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      
      - name: Fetch hidden tests (if available)
        env:
          TESTS_TOKEN: ${{ secrets.TESTS_TOKEN }}
        working-directory: ${{ github.workspace }}
        run: |
          if [ -z "$TESTS_TOKEN" ]; then
            echo "Warning: TESTS_TOKEN not set, skipping private tests"
            mkdir -p tests
          else
            GITEA_HOST=$(echo "${{ github.server_url }}" | sed 's|https\?://||' | cut -d'/' -f1)
            git clone https://oauth2:$TESTS_TOKEN@${GITEA_HOST}/course-test/hw1-tests.git _priv_tests || true
            if [ -d "_priv_tests/python" ]; then
              rsync -a _priv_tests/python/ tests/ || true
            fi
          fi
      
      - name: Run tests using universal test runner
        working-directory: ${{ github.workspace }}
        env:
          LANGUAGE: python
        run: |
          export PYTHONHASHSEED=2025
          python3 ./.autograde/run_tests.py \
            --language python \
            --test-dir tests_public \
            --source-dir src \
            --output-xml junit.xml || true
      
      - name: Grade
        working-directory: ${{ github.workspace }}
        run: |
          python3 ./.autograde/grade.py --junit junit.xml --out grade.json --summary summary.md
      
      - name: Create grade metadata
        working-directory: ${{ github.workspace }}
        env:
          ASSIGNMENT_ID: hw1
          REPO: ${{ github.repository }}
          LANGUAGE: python
        run: |
          if [ ! -f grade.json ]; then
            echo "⚠️ grade.json not found, skipping metadata creation"
            exit 0
          fi
          
          export GRADE_TYPE=programming
          python3 ./.autograde/create_minimal_metadata.py > metadata.json || echo "{}" > metadata.json
          echo "✅ Grade metadata created"
          cat metadata.json
      
      - name: Comment on PR
        env:
          GITEA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_NAME: ${{ github.event_name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_SHA: ${{ github.sha }}
        working-directory: ${{ github.workspace }}
        run: |
          if [ ! -f summary.md ]; then
            echo "⚠️ No summary.md found"
            exit 0
          fi
          
          export COMMENT_SUMMARY=$(cat summary.md)
          export GRADE_METADATA=$(cat metadata.json 2>/dev/null || echo "{}")
          
          python3 ./.autograde/post_comment.py

