# R 编程作业自动评分 Workflow 模板
#
# 使用方法：
# 1. 复制此文件到 .gitea/workflows/grade.yml
# 2. 根据需要调整 R 版本、依赖包等
# 3. 确保项目有正确的 DESCRIPTION 文件

name: autograde-r

on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  r:
    runs-on: docker
    container: r-base:4.3
    timeout-minutes: 20
    
    steps:
      - name: Install system dependencies
        run: |
          set -e
          apt-get update -y
          DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
            git ca-certificates rsync python3 python3-pip \
            libcurl4-openssl-dev libssl-dev libxml2-dev
          rm -rf /var/lib/apt/lists/*
      
      - name: Checkout code
        env:
          TESTS_TOKEN: ${{ secrets.TESTS_TOKEN }}
          EXTERNAL_GITEA_HOST: ${{ secrets.EXTERNAL_GITEA_HOST }}
        working-directory: ${{ github.workspace }}
        run: |
          set -e
          GITEA_HOST=$(echo "${{ github.server_url }}" | sed 's|https\?://||' | cut -d'/' -f1)
          HOST="$GITEA_HOST"
          if echo "$GITEA_HOST" | grep -qi '^gitea'; then
            if [ -n "$EXTERNAL_GITEA_HOST" ]; then
              HOST="$EXTERNAL_GITEA_HOST"
            else
              HOST="49.234.193.192:3000"
            fi
          fi
          REPO="${{ github.repository }}"
          REF="${{ github.sha }}"
          
          git init -q .
          if [ -n "$TESTS_TOKEN" ]; then
            REMOTE_URL="http://oauth2:${TESTS_TOKEN}@${HOST}/${REPO}.git"
          else
            REMOTE_URL="http://${HOST}/${REPO}.git"
          fi
          git remote add origin "$REMOTE_URL" || git remote set-url origin "$REMOTE_URL"
          git fetch --depth=1 origin "$REF"
          git checkout -q FETCH_HEAD
      
      - name: Install R dependencies
        working-directory: ${{ github.workspace }}
        run: |
          # 从 DESCRIPTION 文件安装依赖
          if [ -f DESCRIPTION ]; then
            Rscript -e "install.packages('remotes', repos='https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
            Rscript -e "remotes::install_deps(dependencies = TRUE, repos='https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
          fi
          
          # 确保安装 testthat
          Rscript -e "if (!requireNamespace('testthat', quietly = TRUE)) install.packages('testthat', repos='https://mirrors.tuna.tsinghua.edu.cn/CRAN/')"
      
      - name: Fetch hidden tests (if available)
        env:
          TESTS_TOKEN: ${{ secrets.TESTS_TOKEN }}
        working-directory: ${{ github.workspace }}
        run: |
          if [ -z "$TESTS_TOKEN" ]; then
            echo "Warning: TESTS_TOKEN not set, skipping private tests"
          else
            GITEA_HOST=$(echo "${{ github.server_url }}" | sed 's|https\?://||' | cut -d'/' -f1)
            git clone https://oauth2:$TESTS_TOKEN@${GITEA_HOST}/course-test/r-hw1-tests.git _priv_tests || true
            if [ -d "_priv_tests/tests" ]; then
              rsync -a _priv_tests/tests/ tests/ || true
            fi
          fi
      
      - name: Run tests using testthat
        working-directory: ${{ github.workspace }}
        env:
          LANGUAGE: r
        run: |
          # 使用 testthat 的 JUnitReporter
          Rscript -e "
          library(testthat)
          
          # 配置 JUnit reporter
          reporter <- JunitReporter\$new(file = 'junit.xml')
          
          # 运行测试
          result <- test_dir(
            path = 'tests/testthat',
            reporter = reporter,
            stop_on_failure = FALSE
          )
          
          # 返回状态码（0 表示全部通过）
          if (any(result\$failed > 0)) {
            quit(status = 1)
          }
          " || true
      
      - name: Install Python for grading
        run: |
          pip3 install --break-system-packages python-dotenv
      
      - name: Grade
        working-directory: ${{ github.workspace }}
        run: |
          python3 ./.autograde/grade.py --junit junit.xml --out grade.json --summary summary.md
      
      - name: Create grade metadata
        working-directory: ${{ github.workspace }}
        env:
          ASSIGNMENT_ID: r-hw1
          REPO: ${{ github.repository }}
          LANGUAGE: r
        run: |
          if [ ! -f grade.json ]; then
            echo "⚠️ grade.json not found, skipping metadata creation"
            exit 0
          fi
          
          export GRADE_TYPE=programming
          python3 ./.autograde/create_minimal_metadata.py > metadata.json || echo "{}" > metadata.json
          echo "✅ Grade metadata created"
          cat metadata.json
      
      - name: Comment on PR
        env:
          GITEA_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          EVENT_NAME: ${{ github.event_name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          COMMIT_SHA: ${{ github.sha }}
        working-directory: ${{ github.workspace }}
        run: |
          if [ ! -f summary.md ]; then
            echo "⚠️ No summary.md found"
            exit 0
          fi
          
          export COMMENT_SUMMARY=$(cat summary.md)
          export GRADE_METADATA=$(cat metadata.json 2>/dev/null || echo "{}")
          
          python3 ./.autograde/post_comment.py

